version: '3.8'

services:
  web:
    ports:
      - '8000:8000'
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
